Description: 'EKS Cluster'

Parameters:

  EnvironmentName:
    Description: Env name will be used to tag resources and refer to output parameters in other cloud formation scripts
    Type: String

  VPCEnvironmentName:
    Description: The already created VPC for Kubernetes
    Type: String
  
  IamEnvironmentName:
    Description: The already created IAM role for Kubernetes
    Type: String

  EKSWorkerNodeInstanceType:
      Type: String
      Default: t2.micro
      AllowedValues: [t2.nano, t2.micro]
      ConstraintDescription: Must be a valid EC2 instance type
      Description: EC2 instance type for the node instances
  
  EKSNodeGroupName:
      Type: String
      Default: NodeGroup01
      Description: The desired name of AWS EKS Node Group

  EksKeyPair:
      Type: "AWS::EC2::KeyPair::KeyName"
      Default: "my-eks-key"
      Description: The name of Key Pair to etasblish connection with Worker Nodes

Resources:

  EksClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound http traffic to Eks cluster
      VpcId:
        Fn::ImportValue: !Sub "${VPCEnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  EksCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EnvironmentName
      RoleArn: arn:aws:iam::639584826680:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref EksClusterSecurityGroup
        SubnetIds: 
          - Fn::ImportValue: !Sub "${VPCEnvironmentName}-PUB1-SN"
          - Fn::ImportValue: !Sub "${VPCEnvironmentName}-PUB2-SN"
    DependsOn: [EksClusterSecurityGroup]

  EksNodeGroup:
      Type: AWS::EKS::Nodegroup
      Properties:
        ClusterName: !Ref EksCluster
        NodeRole: arn:aws:iam::639584826680:role/aws-service-role/eks-nodegroup.amazonaws.com/AWSServiceRoleForAmazonEKSNodegroup
        AmiType: AL2_x86_64
        InstanceTypes: 
          - !Ref EKSWorkerNodeInstanceType
        NodegroupName: !Ref EKSNodeGroupName
        RemoteAccess:
          Ec2SshKey: !Ref EksKeyPair
        ScalingConfig:
          MinSize: 1
          DesiredSize: 2
          MaxSize: 7
        Subnets:
          - Fn::ImportValue: !Sub "${VPCEnvironmentName}-PUB1-SN"
          - Fn::ImportValue: !Sub "${VPCEnvironmentName}-PUB2-SN"
      DependsOn: [EksCluster]

Outputs:

  EksClusterEndpoint:
    Description: A reference to the endpoint of the created kubernetes cluster
    Value: !Select [1, !Split ["//", !GetAtt EksCluster.Endpoint]]