version: 2.1

jobs:

  build:
    docker:
      - image: python:3.7.3-stretch
    
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./docker/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            cd docker
            python3 -m venv ~/.venv
            source ~/.venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ~/docker/.venv
          key: v1-dependencies-{{ checksum "./docker/requirements.txt" }}
      - run:
          name: Lint Dockerfile and app source code
          command: |
            cd docker
            source ~/.venv/bin/activate
            pip install pylint
            make lint
      - run:
          name: Build Docker image
          command: |
            cd docker
            source ~/.venv/bin/activate
            make build
      - run:
          name: Push Docker image to docker hub
          command: |
            cd docker
            source ~/.venv/bin/activate
            make push
  
workflows:
  default:
    jobs:
      - build