version: 2.1

jobs:

  lint:
    docker:
      - image: python:3.7.3-stretch
    
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./docker/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            cd docker
            python3 -m venv ~/.venv
            source ~/.venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ~/docker/.venv
          key: v1-dependencies-{{ checksum "./docker/requirements.txt" }}
      - run:
          name: Lint Dockerfile and app source code
          command: |
            cd docker
            source ~/.venv/bin/activate
            pip install pylint
            make lint

  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-dockerfile-{{ checksum "./docker/Dockerfile" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-dockerfile
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            cd docker/app
            export CIRCLE_WORKFLOW=${CIRCLE_WORKFLOW_ID:0:7}
            sed -i "s/REFERENCE_NO/${CIRCLE_WORKFLOW}/g" index.html
            more index.html
            cd ..
            sed -i "s/TARGET_TAG/${CIRCLE_WORKFLOW}/g" Makefile
            more Makefile
            make build
      - run:
          name: Push Docker image to docker hub
          command: |
            cd docker
            make push
      - save_cache:
          paths:
            - ~/docker
          key: v1-dependencies-{{ checksum "./docker/Dockerfile" }}

  deploy:
    docker:
      - image: debian:stretch-slim
    
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - debian:stretch-slim
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y make curl zip gzip tar
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
            echo "$(<kubectl.sha256) kubectl" | sha256sum --check
            install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - run:
          name: Configure kubectl for AWS EKS
          command: |
            cd kube-deploy
            make configure
      - run:
          name: Configure kubectl files
          command: |
            cd kube-deploy
            export CIRCLE_WORKFLOW=${CIRCLE_WORKFLOW_ID:0:7}
            
            # App file
            sed -i "s/TARGET_TAG/${CIRCLE_WORKFLOW}/g" ./app-deploy.yaml
            cat ./app-deploy.yaml

            # Expose node port
            sed -i "s/TARGET_TAG/${CIRCLE_WORKFLOW}/g" ./node-port.yaml
            cat ./node-port.yaml

            # Load balancer
            sed -i "s/TARGET_TAG/${CIRCLE_WORKFLOW}/g" ./load-balancer.yaml
            cat ./load-balancer.yaml

            # Makefile
            sed -i "s/TARGET_TAG/${CIRCLE_WORKFLOW}/g" ./Makefile
            cat ./Makefile

            # Scripts
            sed -i "s/TARGET_TAG/${CIRCLE_WORKFLOW}/g" ./scripts/CheckBlue.sh
            cat ./scripts/CheckBlue.sh

            sed -i "s/TARGET_TAG/${CIRCLE_WORKFLOW}/g" ./scripts/DestroyBlue.sh
            cat ./scripts/DestroyBlue.sh

            echo "All files are configured!"
      - run:
          name: Deploy blue instance
          command: |
            cd kube-deploy
            make deploy-blue
      - run:
          name: Check blue instance
          command: |
            cd kube-deploy
            make check-blue
      - run:
          name: Switch load balancer to target the new app
          command: |
            cd kube-deploy
            make switch-load-balancer
      - run:
          name: Destroy old version
          command: |
            cd kube-deploy
            make destroy-old-version
      - save_cache:
          paths:
            - ~/kube-deploy
          key: debian:stretch-slim

workflows:
  default:
    jobs:
      - lint
      - build:
          requires: [lint]
      - deploy:
          requires: [build]