apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-nginx-deployment
  labels:
    app: sampleapp-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sampleapp-nginx
  template:
    metadata:
      labels:
        app: sampleapp-nginx
    spec:
      containers:
      - name: sampleapp-nginx
        image: bishoy/sampleapp:TARGET_TAG
        ports:
        - containerPort: 80