apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-deployment-TARGET_TAG
  labels:
    app: sampleapp-TARGET_TAG
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: bishoy/sampleapp:TARGET_TAG
        ports:
        - containerPort: 80