apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-auto-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-auto-scaler
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50