apiVersion: v1
kind: Service
metadata:
  name: sampleapp-nginx-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: sampleapp-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80