apiVersion: v1
kind: Service
metadata:
  name: nginx-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: sampleapp-TARGET_TAG
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80